[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "https://www.reddit.com/:splat"
  status = 200
  force = true
  headers = {Accept = "application/json"}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200